// Generated by scripts/gen-binding-register.mjs — do not edit by hand.
#include <napi.h>

#include "binding_batch.hpp"
#include "binding_init.hpp"
#include "binding_state.hpp"

Napi::Value EvaluateBestHand(const Napi::CallbackInfo& info);
Napi::Value EvaluateHandStrength(const Napi::CallbackInfo& info);
Napi::Value EvaluateHandStrengthFast(const Napi::CallbackInfo& info);
Napi::Value BenchmarkEvaluatorThroughput(const Napi::CallbackInfo& info);
Napi::Value BenchmarkEvaluatorThroughputAsync(const Napi::CallbackInfo& info);
Napi::Value EvaluateHandCategory(const Napi::CallbackInfo& info);
Napi::Value ValidateCardString(const Napi::CallbackInfo& info);
Napi::Value CardStringsHaveDuplicate(const Napi::CallbackInfo& info);
Napi::Value CanonicalCardString(const Napi::CallbackInfo& info);
Napi::Value ParseCompactCardList(const Napi::CallbackInfo& info);
Napi::Value CompareBestHands(const Napi::CallbackInfo& info);
Napi::Value SimulateHandOutcome(const Napi::CallbackInfo& info);
Napi::Value SimulateHandOutcomeAsync(const Napi::CallbackInfo& info);
Napi::Value ParallelHandSimulation(const Napi::CallbackInfo& info);
Napi::Value ParallelHandSimulationAsync(const Napi::CallbackInfo& info);
Napi::Value DecideAction(const Napi::CallbackInfo& info);
Napi::Value DecideActionAsync(const Napi::CallbackInfo& info);
Napi::Value PotOddsRatio(const Napi::CallbackInfo& info);
Napi::Value ExpectedValueCall(const Napi::CallbackInfo& info);
Napi::Value ExpectedValueCallWithRake(const Napi::CallbackInfo& info);
Napi::Value Spr(const Napi::CallbackInfo& info);
Napi::Value EffectiveStack(const Napi::CallbackInfo& info);
Napi::Value NormalizedStackFractions(const Napi::CallbackInfo& info);
Napi::Value BreakevenCallEquity(const Napi::CallbackInfo& info);
Napi::Value MinimumDefenseFrequency(const Napi::CallbackInfo& info);
Napi::Value StackInBigBlinds(const Napi::CallbackInfo& info);
Napi::Value PotOddsRatioDisplay(const Napi::CallbackInfo& info);
Napi::Value FormatPotOdds(const Napi::CallbackInfo& info);
Napi::Value BreakevenCallEquityFromPotOddsDisplayRatio(const Napi::CallbackInfo& info);
Napi::Value PotOddsDisplayRatioFromBreakevenCallEquity(const Napi::CallbackInfo& info);
Napi::Value FormatPotOddsReducedFraction(const Napi::CallbackInfo& info);
Napi::Value EquityToWinningOddsAgainst(const Napi::CallbackInfo& info);
Napi::Value WinningOddsAgainstToEquity(const Napi::CallbackInfo& info);
Napi::Value RuleOfFourEquity(const Napi::CallbackInfo& info);
Napi::Value RuleOfTwoEquity(const Napi::CallbackInfo& info);
Napi::Value EstimatedOutsFromRuleOfTwo(const Napi::CallbackInfo& info);
Napi::Value EstimatedOutsFromRuleOfFour(const Napi::CallbackInfo& info);
Napi::Value ImpliedBreakevenFutureWin(const Napi::CallbackInfo& info);
Napi::Value BluffToValueRatio(const Napi::CallbackInfo& info);
Napi::Value ValueToBluffRatio(const Napi::CallbackInfo& info);
Napi::Value BetAsPotFraction(const Napi::CallbackInfo& info);
Napi::Value SprAfterCall(const Napi::CallbackInfo& info);
Napi::Value CommitmentRatio(const Napi::CallbackInfo& info);
Napi::Value AlphaFrequency(const Napi::CallbackInfo& info);
Napi::Value BreakevenFoldEquityPureBluff(const Napi::CallbackInfo& info);
Napi::Value BreakevenFoldEquitySemiBluff(const Napi::CallbackInfo& info);
Napi::Value HypergeometricOneCardHitProbability(const Napi::CallbackInfo& info);
Napi::Value RunnerRunnerBackdoorFlushTwoCardProbability(const Napi::CallbackInfo& info);
Napi::Value FlopToRiverAtLeastOneHitProbability(const Napi::CallbackInfo& info);
Napi::Value FlopToRiverAtLeastOneHitUnionTwoCategories(const Napi::CallbackInfo& info);
Napi::Value FlopToRiverAtLeastOneHitUnionThreeCategories(const Napi::CallbackInfo& info);
Napi::Value FlopToRiverAtLeastOneHitUnionFourCategories(const Napi::CallbackInfo& info);
Napi::Value FlopToRiverAtLeastOneHitDisjointOutsSum(const Napi::CallbackInfo& info);
Napi::Value RunnerRunnerStraightDrawHitProbability(const Napi::CallbackInfo& info);
Napi::Value ReverseImpliedOddsMaxFutureLoss(const Napi::CallbackInfo& info);
Napi::Value GeometricPotAfterMatchedPotFractions(const Napi::CallbackInfo& info);
Napi::Value HarringtonM(const Napi::CallbackInfo& info);
Napi::Value HarringtonMEffective(const Napi::CallbackInfo& info);
Napi::Value HarringtonMEffectiveActiveAntes(const Napi::CallbackInfo& info);
Napi::Value HarringtonQ(const Napi::CallbackInfo& info);
Napi::Value OrbitCostChips(const Napi::CallbackInfo& info);
Napi::Value NlMinimumRaiseToTotal(const Napi::CallbackInfo& info);
Napi::Value PreflopCombosFromNotation(const Napi::CallbackInfo& info);
Napi::Value PreflopCombosFromNotationsList(const Napi::CallbackInfo& info);
Napi::Value HandRankCategoryOrder(const Napi::CallbackInfo& info);
Napi::Value KellyCriterionBinary(const Napi::CallbackInfo& info);
Napi::Value MonteCarloStandardError(const Napi::CallbackInfo& info);
Napi::Value MonteCarloTrialsForStandardErrorBound(const Napi::CallbackInfo& info);
Napi::Value BetaBinomialFoldPosterior(const Napi::CallbackInfo& info);
Napi::Value DuplicationAdjustedOuts(const Napi::CallbackInfo& info);
Napi::Value RiskOfRuinDiffusionApprox(const Napi::CallbackInfo& info);
Napi::Value BankrollForTargetRorDiffusion(const Napi::CallbackInfo& info);
Napi::Value WilsonScoreInterval(const Napi::CallbackInfo& info);
Napi::Value AgrestiCoullInterval(const Napi::CallbackInfo& info);
Napi::Value NormalWaldBinomialInterval(const Napi::CallbackInfo& info);
Napi::Value MonteCarloTrialsForHoeffdingBound(const Napi::CallbackInfo& info);
Napi::Value RakeFromPot(const Napi::CallbackInfo& info);
Napi::Value BreakevenCallEquityWithRake(const Napi::CallbackInfo& info);
Napi::Value BreakevenFoldEquitySemiBluffWithRake(const Napi::CallbackInfo& info);
Napi::Value BreakevenFoldEquityPureBluffWithRake(const Napi::CallbackInfo& info);
Napi::Value MultiwaySymmetricBreakevenCallEquity(const Napi::CallbackInfo& info);
Napi::Value MultiwaySymmetricBreakevenCallEquityWithShare(const Napi::CallbackInfo& info);
Napi::Value TwoStreetPureBluffSameFoldEquity(const Napi::CallbackInfo& info);
Napi::Value TwoStreetPureBluffEv(const Napi::CallbackInfo& info);
Napi::Value BreakevenFoldEquitySecondStreetPureBluff(const Napi::CallbackInfo& info);
Napi::Value BreakevenFoldEquityFirstStreetPureBluff(const Napi::CallbackInfo& info);
Napi::Value ChubukovSymmetricJamBreakevenStack(const Napi::CallbackInfo& info);
Napi::Value ChubukovSymmetricJamEv(const Napi::CallbackInfo& info);
Napi::Value ChubukovMaxSymmetricJamStackChipsBinarySearch(const Napi::CallbackInfo& info);
Napi::Value IcmWinProbabilitiesHarville(const Napi::CallbackInfo& info);
Napi::Value IcmHarvillePlacementProbabilities(const Napi::CallbackInfo& info);
Napi::Value IcmTopKFinishProbabilities(const Napi::CallbackInfo& info);
Napi::Value IcmLastPlaceProbabilitiesHarville(const Napi::CallbackInfo& info);
Napi::Value IcmExpectedPayouts(const Napi::CallbackInfo& info);
Napi::Value IcmPairwiseBubbleFactor(const Napi::CallbackInfo& info);
Napi::Value SidePotLadderFromCommitments(const Napi::CallbackInfo& info);
Napi::Value LayeredPotChipEvFromEquities(const Napi::CallbackInfo& info);
Napi::Value SidePotLayersTotalChips(const Napi::CallbackInfo& info);
Napi::Value ExactHuEquityVsRandomHand(const Napi::CallbackInfo& info);
Napi::Value ExactHuEquityVsRandomHandAsync(const Napi::CallbackInfo& info);
Napi::Value StraightMadeFlopToRiverExactProbability(const Napi::CallbackInfo& info);
Napi::Value StraightMadeFlopToRiverExactProbabilityAsync(const Napi::CallbackInfo& info);
Napi::Value ChubukovMaxSymmetricJamStackBinarySearch(const Napi::CallbackInfo& info);
Napi::Value ChubukovMaxSymmetricJamStackFromHandBinarySearch(const Napi::CallbackInfo& info);
Napi::Value SimulateHandOutcomeBatch(const Napi::CallbackInfo& info);
Napi::Value SimulateHandOutcomeBatchPacked(const Napi::CallbackInfo& info);
Napi::Value EvaluateHandStrengthFastBatch(const Napi::CallbackInfo& info);
Napi::Value ExactHuEquityVsRandomHandBatch(const Napi::CallbackInfo& info);

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    poker_bind::init_binding(env);
    exports.DefineProperties({
        Napi::PropertyDescriptor::Function("evaluateBestHand", EvaluateBestHand),
        Napi::PropertyDescriptor::Function("evaluateHandStrength", EvaluateHandStrength),
        Napi::PropertyDescriptor::Function("evaluateHandStrengthFast", EvaluateHandStrengthFast),
        Napi::PropertyDescriptor::Function("benchmarkEvaluatorThroughput", BenchmarkEvaluatorThroughput),
        Napi::PropertyDescriptor::Function("benchmarkEvaluatorThroughputAsync", BenchmarkEvaluatorThroughputAsync),
        Napi::PropertyDescriptor::Function("evaluateHandCategory", EvaluateHandCategory),
        Napi::PropertyDescriptor::Function("validateCardString", ValidateCardString),
        Napi::PropertyDescriptor::Function("cardStringsHaveDuplicate", CardStringsHaveDuplicate),
        Napi::PropertyDescriptor::Function("canonicalCardString", CanonicalCardString),
        Napi::PropertyDescriptor::Function("parseCompactCardList", ParseCompactCardList),
        Napi::PropertyDescriptor::Function("compareBestHands", CompareBestHands),
        Napi::PropertyDescriptor::Function("simulateHandOutcome", SimulateHandOutcome),
        Napi::PropertyDescriptor::Function("simulateHandOutcomeAsync", SimulateHandOutcomeAsync),
        Napi::PropertyDescriptor::Function("parallelHandSimulation", ParallelHandSimulation),
        Napi::PropertyDescriptor::Function("parallelHandSimulationAsync", ParallelHandSimulationAsync),
        Napi::PropertyDescriptor::Function("decideAction", DecideAction),
        Napi::PropertyDescriptor::Function("decideActionAsync", DecideActionAsync),
        Napi::PropertyDescriptor::Function("potOddsRatio", PotOddsRatio),
        Napi::PropertyDescriptor::Function("expectedValueCall", ExpectedValueCall),
        Napi::PropertyDescriptor::Function("expectedValueCallWithRake", ExpectedValueCallWithRake),
        Napi::PropertyDescriptor::Function("spr", Spr),
        Napi::PropertyDescriptor::Function("effectiveStack", EffectiveStack),
        Napi::PropertyDescriptor::Function("normalizedStackFractions", NormalizedStackFractions),
        Napi::PropertyDescriptor::Function("breakevenCallEquity", BreakevenCallEquity),
        Napi::PropertyDescriptor::Function("minimumDefenseFrequency", MinimumDefenseFrequency),
        Napi::PropertyDescriptor::Function("stackInBigBlinds", StackInBigBlinds),
        Napi::PropertyDescriptor::Function("potOddsRatioDisplay", PotOddsRatioDisplay),
        Napi::PropertyDescriptor::Function("formatPotOdds", FormatPotOdds),
        Napi::PropertyDescriptor::Function("breakevenCallEquityFromPotOddsDisplayRatio", BreakevenCallEquityFromPotOddsDisplayRatio),
        Napi::PropertyDescriptor::Function("potOddsDisplayRatioFromBreakevenCallEquity", PotOddsDisplayRatioFromBreakevenCallEquity),
        Napi::PropertyDescriptor::Function("formatPotOddsReducedFraction", FormatPotOddsReducedFraction),
        Napi::PropertyDescriptor::Function("equityToWinningOddsAgainst", EquityToWinningOddsAgainst),
        Napi::PropertyDescriptor::Function("winningOddsAgainstToEquity", WinningOddsAgainstToEquity),
        Napi::PropertyDescriptor::Function("ruleOfFourEquity", RuleOfFourEquity),
        Napi::PropertyDescriptor::Function("ruleOfTwoEquity", RuleOfTwoEquity),
        Napi::PropertyDescriptor::Function("estimatedOutsFromRuleOfTwo", EstimatedOutsFromRuleOfTwo),
        Napi::PropertyDescriptor::Function("estimatedOutsFromRuleOfFour", EstimatedOutsFromRuleOfFour),
        Napi::PropertyDescriptor::Function("impliedBreakevenFutureWin", ImpliedBreakevenFutureWin),
        Napi::PropertyDescriptor::Function("bluffToValueRatio", BluffToValueRatio),
        Napi::PropertyDescriptor::Function("valueToBluffRatio", ValueToBluffRatio),
        Napi::PropertyDescriptor::Function("betAsPotFraction", BetAsPotFraction),
        Napi::PropertyDescriptor::Function("sprAfterCall", SprAfterCall),
        Napi::PropertyDescriptor::Function("commitmentRatio", CommitmentRatio),
        Napi::PropertyDescriptor::Function("alphaFrequency", AlphaFrequency),
        Napi::PropertyDescriptor::Function("breakevenFoldEquityPureBluff", BreakevenFoldEquityPureBluff),
        Napi::PropertyDescriptor::Function("breakevenFoldEquitySemiBluff", BreakevenFoldEquitySemiBluff),
        Napi::PropertyDescriptor::Function("hypergeometricOneCardHitProbability", HypergeometricOneCardHitProbability),
        Napi::PropertyDescriptor::Function("runnerRunnerBackdoorFlushTwoCardProbability", RunnerRunnerBackdoorFlushTwoCardProbability),
        Napi::PropertyDescriptor::Function("flopToRiverAtLeastOneHitProbability", FlopToRiverAtLeastOneHitProbability),
        Napi::PropertyDescriptor::Function("flopToRiverAtLeastOneHitUnionTwoCategories", FlopToRiverAtLeastOneHitUnionTwoCategories),
        Napi::PropertyDescriptor::Function("flopToRiverAtLeastOneHitUnionThreeCategories", FlopToRiverAtLeastOneHitUnionThreeCategories),
        Napi::PropertyDescriptor::Function("flopToRiverAtLeastOneHitUnionFourCategories", FlopToRiverAtLeastOneHitUnionFourCategories),
        Napi::PropertyDescriptor::Function("flopToRiverAtLeastOneHitDisjointOutsSum", FlopToRiverAtLeastOneHitDisjointOutsSum),
        Napi::PropertyDescriptor::Function("runnerRunnerStraightDrawHitProbability", RunnerRunnerStraightDrawHitProbability),
        Napi::PropertyDescriptor::Function("reverseImpliedOddsMaxFutureLoss", ReverseImpliedOddsMaxFutureLoss),
        Napi::PropertyDescriptor::Function("geometricPotAfterMatchedPotFractions", GeometricPotAfterMatchedPotFractions),
        Napi::PropertyDescriptor::Function("harringtonM", HarringtonM),
        Napi::PropertyDescriptor::Function("harringtonMEffective", HarringtonMEffective),
        Napi::PropertyDescriptor::Function("harringtonMEffectiveActiveAntes", HarringtonMEffectiveActiveAntes),
        Napi::PropertyDescriptor::Function("harringtonQ", HarringtonQ),
        Napi::PropertyDescriptor::Function("orbitCostChips", OrbitCostChips),
        Napi::PropertyDescriptor::Function("nlMinimumRaiseToTotal", NlMinimumRaiseToTotal),
        Napi::PropertyDescriptor::Function("preflopCombosFromNotation", PreflopCombosFromNotation),
        Napi::PropertyDescriptor::Function("preflopCombosFromNotationsList", PreflopCombosFromNotationsList),
        Napi::PropertyDescriptor::Function("handRankCategoryOrder", HandRankCategoryOrder),
        Napi::PropertyDescriptor::Function("kellyCriterionBinary", KellyCriterionBinary),
        Napi::PropertyDescriptor::Function("monteCarloStandardError", MonteCarloStandardError),
        Napi::PropertyDescriptor::Function("monteCarloTrialsForStandardErrorBound", MonteCarloTrialsForStandardErrorBound),
        Napi::PropertyDescriptor::Function("betaBinomialFoldPosterior", BetaBinomialFoldPosterior),
        Napi::PropertyDescriptor::Function("duplicationAdjustedOuts", DuplicationAdjustedOuts),
        Napi::PropertyDescriptor::Function("riskOfRuinDiffusionApprox", RiskOfRuinDiffusionApprox),
        Napi::PropertyDescriptor::Function("bankrollForTargetRorDiffusion", BankrollForTargetRorDiffusion),
        Napi::PropertyDescriptor::Function("wilsonScoreInterval", WilsonScoreInterval),
        Napi::PropertyDescriptor::Function("agrestiCoullInterval", AgrestiCoullInterval),
        Napi::PropertyDescriptor::Function("normalWaldBinomialInterval", NormalWaldBinomialInterval),
        Napi::PropertyDescriptor::Function("monteCarloTrialsForHoeffdingBound", MonteCarloTrialsForHoeffdingBound),
        Napi::PropertyDescriptor::Function("rakeFromPot", RakeFromPot),
        Napi::PropertyDescriptor::Function("breakevenCallEquityWithRake", BreakevenCallEquityWithRake),
        Napi::PropertyDescriptor::Function("breakevenFoldEquitySemiBluffWithRake", BreakevenFoldEquitySemiBluffWithRake),
        Napi::PropertyDescriptor::Function("breakevenFoldEquityPureBluffWithRake", BreakevenFoldEquityPureBluffWithRake),
        Napi::PropertyDescriptor::Function("multiwaySymmetricBreakevenCallEquity", MultiwaySymmetricBreakevenCallEquity),
        Napi::PropertyDescriptor::Function("multiwaySymmetricBreakevenCallEquityWithShare", MultiwaySymmetricBreakevenCallEquityWithShare),
        Napi::PropertyDescriptor::Function("twoStreetPureBluffSameFoldEquity", TwoStreetPureBluffSameFoldEquity),
        Napi::PropertyDescriptor::Function("twoStreetPureBluffEv", TwoStreetPureBluffEv),
        Napi::PropertyDescriptor::Function("breakevenFoldEquitySecondStreetPureBluff", BreakevenFoldEquitySecondStreetPureBluff),
        Napi::PropertyDescriptor::Function("breakevenFoldEquityFirstStreetPureBluff", BreakevenFoldEquityFirstStreetPureBluff),
        Napi::PropertyDescriptor::Function("chubukovSymmetricJamBreakevenStack", ChubukovSymmetricJamBreakevenStack),
        Napi::PropertyDescriptor::Function("chubukovSymmetricJamEv", ChubukovSymmetricJamEv),
        Napi::PropertyDescriptor::Function("chubukovMaxSymmetricJamStackChipsBinarySearch", ChubukovMaxSymmetricJamStackChipsBinarySearch),
        Napi::PropertyDescriptor::Function("icmWinProbabilitiesHarville", IcmWinProbabilitiesHarville),
        Napi::PropertyDescriptor::Function("icmHarvillePlacementProbabilities", IcmHarvillePlacementProbabilities),
        Napi::PropertyDescriptor::Function("icmTopKFinishProbabilities", IcmTopKFinishProbabilities),
        Napi::PropertyDescriptor::Function("icmLastPlaceProbabilitiesHarville", IcmLastPlaceProbabilitiesHarville),
        Napi::PropertyDescriptor::Function("icmExpectedPayouts", IcmExpectedPayouts),
        Napi::PropertyDescriptor::Function("icmPairwiseBubbleFactor", IcmPairwiseBubbleFactor),
        Napi::PropertyDescriptor::Function("sidePotLadderFromCommitments", SidePotLadderFromCommitments),
        Napi::PropertyDescriptor::Function("layeredPotChipEvFromEquities", LayeredPotChipEvFromEquities),
        Napi::PropertyDescriptor::Function("sidePotLayersTotalChips", SidePotLayersTotalChips),
        Napi::PropertyDescriptor::Function("exactHuEquityVsRandomHand", ExactHuEquityVsRandomHand),
        Napi::PropertyDescriptor::Function("exactHuEquityVsRandomHandAsync", ExactHuEquityVsRandomHandAsync),
        Napi::PropertyDescriptor::Function("straightMadeFlopToRiverExactProbability", StraightMadeFlopToRiverExactProbability),
        Napi::PropertyDescriptor::Function("straightMadeFlopToRiverExactProbabilityAsync", StraightMadeFlopToRiverExactProbabilityAsync),
        Napi::PropertyDescriptor::Function("chubukovMaxSymmetricJamStackBinarySearch", ChubukovMaxSymmetricJamStackBinarySearch),
        Napi::PropertyDescriptor::Function("chubukovMaxSymmetricJamStackFromHandBinarySearch", ChubukovMaxSymmetricJamStackFromHandBinarySearch),
        Napi::PropertyDescriptor::Function("simulateHandOutcomeBatch", SimulateHandOutcomeBatch),
        Napi::PropertyDescriptor::Function("simulateHandOutcomeBatchPacked", SimulateHandOutcomeBatchPacked),
        Napi::PropertyDescriptor::Function("evaluateHandStrengthFastBatch", EvaluateHandStrengthFastBatch),
        Napi::PropertyDescriptor::Function("exactHuEquityVsRandomHandBatch", ExactHuEquityVsRandomHandBatch),
        Napi::PropertyDescriptor::Function("encodePokerState", poker_bind::EncodePokerState),
        Napi::PropertyDescriptor::Function("decodePokerState", poker_bind::DecodePokerState),
    });
    return exports;
}

NODE_API_MODULE(poker_calculations, Init)
